controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      state_publish_rate: 100.0
      action_monitor_rate: 100.0
    arm_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"
      
arm_controller: 
  ros__parameters:
    joints:
      - 6RJ1
      - 6RJ2
      - 6RJ3
      - 6RJ4
      - 6RJ5
      - 6RJ6
    
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0
    action_monitor_rate: 100.0
    interpolation_method: splines
    open_loop_control: false

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      6RJ1:
        goal: 0.1
        trajectory: 0.1
      6RJ2:
        goal: 0.1
        trajectory: 0.1
      6RJ3:
        goal: 0.1
        trajectory: 0.1
      6RJ4:
        goal: 0.1
        trajectory: 0.1
      6RJ5:
        goal: 0.1
        trajectory: 0.1
      6RJ6:
        goal: 0.1
        trajectory: 0.1

    gains:
      6RJ1:
        angle_wraparound: false
        d: 10.0
        ff_velocity_scale: 0.0
        i: 1.0
        i_clamp: 1.0
        normalize_error: false
        p: 100.0
      6RJ2:
        angle_wraparound: false
        d: 1.0
        ff_velocity_scale: 0.0
        i: 1.0
        i_clamp: 1.0
        normalize_error: false
        p: 100.0
      6RJ3:
        angle_wraparound: false
        d: 10.0
        ff_velocity_scale: 0.0
        i: 1.0
        i_clamp: 1.0
        normalize_error: false
        p: 1000.0
      6RJ4:
        angle_wraparound: false
        d: 10.0
        ff_velocity_scale: 0.0
        i: 1.0
        i_clamp: 1.0
        normalize_error: false
        p: 100.0
      6RJ5:
        angle_wraparound: false
        d: 10.0
        ff_velocity_scale: 0.0
        i: 1.0
        i_clamp: 1.0
        normalize_error: false
        p: 100.0
      6RJ6:
        angle_wraparound: false
        d: 10.0
        ff_velocity_scale: 0.0
        i: 1.0
        i_clamp: 1.0
        normalize_error: false
        p: 100.0