# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - 6RJ1
      - 6RJ2
      - 6RJ3
      - 6RJ4
      - 6RJ5
      - 6RJ6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity